import opinion from "../assets/opinion.jpeg";
import editor from "../assets/editor.jpeg";
import  netflixclone from "../assets/netflixclone.jpg";
import todoo from "../assets/todoo.jpg";
import movie from "../assets/movie.jpg";
import qr from "../assets/qr.jpg";
import calc from "../assets/calc.jpg";


export  const Data1 =[
  
    {
        id:1,
        image:todoo,
        title:"Todo List",
        description:"Todo list is developed by using React.",
        link1:"https://github.com/Jackraheem/fff",
        link:"https://raheemtodoapp.netlify.app"
    },
    {
        id:2,
        image:qr,
        title:"QR Generator",
        description:"QR Generated by taking input as text  or URL",
        link1:"https://github.com/Jackraheem/Qr-Generation-by-text",
        link:"https://jackraheemqrgenerate.netlify.app/"

    },
    {
        id:3,
        image:movie,
        title:"Movie Poster Find",
        description:"movie poster searching build by using React",
        link1:"https://github.com/Jackraheem/movie",
        link:"https://jackraheemmovieposter.netlify.app/"

    },
    {
        id:4,
        image:netflixclone,
        title:"NetFlix Clone",
        description:"Using React.js,Firebase.",
        link1:"https://github.com/Jackraheem/netflixClone",
        link:"https://netflix-gpt-jack.onrender.com/"
    },
    {
        id:5,
        image:editor,
        title:"HTML editor ",
        description:"using HTML,css,js to build ",
        link1:"https://github.com/Jackraheem/HTML-editor",
        link:"https://jackraheem.github.io/HTML-editor/"

    },
    {
        id:6,
        image:calc,
        title:"Calculator",
        description:"Calculator by using HTML,CSS,JS ",
        link1:"https://github.com/Jackraheem/calculator/tree/main",
        link:"https://raheemcalculator.netlify.app/"
    },
    {
        id:7,
        image:opinion,
        title:"Opinion Mining for feedback system (Python)",
        description:"This project helps to creating rating by comments using python",
        link1:"https://github.com/Jackraheem/Opinion-Mining-For-feedback-Management-Systems",
        link:"https://github.com/Jackraheem/Opinion-Mining-For-feedback-Management-Systems"

    },
   

]

